# Generated by Django 3.1.7 on 2021-02-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('wildlife', 'WILDLIFE'), ('landscape', 'LANDSCAPE'), ('portrait', 'PORTRAIT'), ('aerial', 'AERIAL'), ('sports', 'SPORTS')], max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'Gallery',
                'ordering': ('-added_on',),
            },
        ),
    ]
