# Generated by Django 3.1.7 on 2021-02-20 10:32

from django.db import migrations, models
import gallery.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to=gallery.helpers.get_or_create_category_directory_path),
        ),
    ]
