# Generated by Django 3.1.7 on 2021-02-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20210220_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('wildlife', 'Wildlife'), ('landscape', 'Landscape'), ('portrait', 'Portrait'), ('aerial', 'Aerial'), ('sports', 'Sports'), ('other', 'Other')], max_length=20),
        ),
    ]
