# Generated by Django 3.1.7 on 2021-02-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20210220_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('aerial', 'Aerial'), ('landscape', 'Landscape'), ('other', 'Other'), ('portrait', 'Portrait'), ('sports', 'Sports'), ('wildlife', 'Wildlife')], max_length=20),
        ),
    ]
